### Variables
@host = http://localhost:3000
@id = 8

### Get Restaurants
GET {{host}}/restaurants

### Delete Restaurant
DELETE {{host}}/restaurants/{{id}}

### Update Restaurant
PUT {{host}}/restaurants/{{id}}
Content-Type: application/json

{
    "id": 8,
    "name": "Hooters",
    "address": "280 Adelaide St W, Toronto, ON M5V 1P6",
    "rating": 4.5
}

### Add Restaurant
POST {{host}}/restaurants
Content-Type: application/json

{
    "name": "Red Lobster",
    "address": "I don't know",
    "rating": 4.8
}